# Generated by Django 5.2.6 on 2025-09-27 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.CharField(blank=True, help_text='e.g., 123 Banana St, Osu', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='A wide banner image for your storefront (e.g., 1200x400 pixels).', null=True, upload_to='vendor_banners/'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='location',
            field=models.CharField(blank=True, help_text='e.g., Accra, Greater Accra Region', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
